### PR TITLE
Move the swap modal progressbar to the top of the modal

### PR DESCRIPTION
**Pull request by sindresorhus**
Per request in #177. I'm still undecided on this.

@lukechilds @kevva Thoughts?

#### Before

screen shot 2018-07-20 at 18 37 57

#### After

screen shot 2018-07-20 at 18 27 58
screen shot 2018-07-20 at 18 27 49

### CODE REVIEW

**Comment by lukechilds** [comment]
I definitely prefer it visually, when the progress bar is at the top.

However it's nice in the previous version that the progress bar and "swap n/5" text are right next to each other. The progress text looks a little out of place on the current version.

One potential solution would be to keep the progress bar at the top, have the status text in the modal body as "Swapping" and add "Swap n/5" to the title, so it's visually associated with the progress bar again.

Thoughts?

**Comment by sindresorhus** [comment]
@lukechilds How about this? In the title, have the status on the left side, the type of order on the middle and the date on the right side? (And make the left/right darker or smaller to highlight the center one)

screen shot 2018-07-24 at 04 04 30

**Comment by kevva** [comment]
> And make the left/right darker or smaller to highlight the center one (Not done in the screenshot).

Yes. Looks pretty crowded in the screenshot. Not sure how obvious it'd be that the   top left status (like 3/5 swaps) ties into the progress bar. The `Completed` status looks pretty nice to me though. Definitely like it better at the top.

**Comment by lukechilds** [comment]
@sindresorhus I really like that.

Assuming we'll use the formatted status in the top left so it'll be "Swap 2/5" not "Swapping"?

**Comment by sindresorhus** [comment]
This is not yet ready to be merged. I have to implement what was decided on here.

**Comment by sindresorhus** [comment]
The screenshot was just a quick mockup :p

**Comment by lukechilds** [comment]
Woops, got a bit trigger happy on the review button.

**Comment by sindresorhus** [comment]
How it looks now:

screen shot 2018-07-30 at 21 33 41
screen shot 2018-07-30 at 21 33 48

Thoughts?

**Comment by lukechilds** [comment]
I like it.

Shouldn't there be a red bar at the top of the failed swap?

**Comment by sindresorhus** [comment]
> Shouldn't there be a red bar at the top of the failed swap?

There is no red bar as there is no progress. It failed at the pre-step. Do you think it would make sense to still force a 100% red progress bar?

**Comment by lukechilds** [comment]
Ah of course, I think so yeah, just for consistency.

**Comment by sindresorhus** [comment]
Done

**Pull request merged**
