### PR TITLE
Add native Romanian (RO) translation

### PR DESCRIPTION
**Pull request by capital-technologies**

### CODE REVIEW

**Comment by lukechilds** [comment]
@capital-technologies Thanks so much for taking the time to do this 🙏 

Looks good to me but will wait for @sindresorhus or @kevva to give it the once over before merging as I haven't had much to do with localisation.

**Comment by capital-technologies** [comment]
@sindresorhus , @kevva , @lukechilds any updates on this?

**Comment by lukechilds** [comment]
@capital-technologies yeah, we use a provider called CrowdIn to manage translations. It currently only supports one-way sync (CrowndIn => GitHub) not two-way support (GitHub => CrowdIn) like in this PR.

@sindresorhus thinks he can resync these changes over to CrowdIn but if we just merge this right now we're not quite sure what will happen and it might break CrowdIn. We don't want to risk that right before the Beta launch so we'll release without it but will look into this after.

We'll keep you posted.

**Comment by sindresorhus** [comment]
Ok, the sync trick worked.

**Comment by sindresorhus** [comment]
@capital-technologies There's a couple of remaining string to translate. Would you be able to do them too? https://crowdin.com/translate/hyperdex/34/en-ro (Use the CrowdIn UI, not GitHub)

**Comment by capital-technologies** [comment]
@sindresorhus I filled the missing gaps, everything's ok now.

**Comment by sindresorhus** [comment]
Perfect. Thank you :)

**Pull request merged**
