### PR TITLE
Move enabled currencies from the app config to the portfolio

### LINKED ISSUE #471: Store the enabled currencies in the portfolio itself, not in the app settings file
This will be important for when we allow import/export of portfolios (#454), but also now, so new portfolios get new default currencies we add (https://github.com/atomiclabs/hyperdex/issues/469#issuecomment-412145712).

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #471 and paves the way for #454.

Includes automatic migration.

### CODE REVIEW

**Comment by kevva** [comment]
The first time I logged in I got the error below. After trying again it worked fine. Adding/removing currencies also works and shows up in the portfolio file as expected.

screenshot 2018-12-05 at 18 11 46

**Comment by sindresorhus** [comment]
@kevva Thanks, missed that. Fixed.

**Comment by kevva** [comment]
Hmm, I still get the error. To reproduce; remove `currencies` from the portfolio file and try logging in.

**Comment by kevva** [comment]
I get this when starting the app now:

screenshot 2018-12-08 at 15 54 05

**Comment by sindresorhus** [comment]
@kevva I'm still unable to reproduce your issue, but I've tried a different approach to fix https://github.com/atomiclabs/hyperdex/pull/575#issuecomment-444566947. Can you reproduce the missing portfolio issue with the latest commit?

**Comment by kevva** [comment]
@sindresorhus, strange. I got it sometimes, and sometimes it worked. However, with this new solution, it never seems to occur so I think this should be ready now! Great work!

**Pull request merged**
