### PR TITLE
Add more currencies and update some Electrum servers

### PR DESCRIPTION
**Pull request by sindresorhus**
Just a regular update from https://github.com/jl777/coins

Changes: https://github.com/jl777/coins/compare/ea1c8c7b5135a4e39021fae8bc08934588f24e4c...74bd464e6a353f1ace064a631b3798cc64fcbff7

I have manually tried all the new coins and they seem to work.

Added currencies:
- GBX
- SMART
- STAK
- MAC
- MNX
- CALL
- VRSC
- CC
- FTC
- POLIS
- XMCC
- XZC

### CODE REVIEW

**Comment by lukechilds** [comment]
I know a lot of people have requested VRSC. Did you manage to make a trade? I can deposit but not seeing anything in the order book.

**Comment by sindresorhus** [comment]
I've been trying to buy some VRSC all day, but the orders just stay at `Open` status.

**Comment by lukechilds** [comment]
Have you seen anything in the order book? It could just be their are no Bobs.

**Comment by lukechilds** [comment]
Yep, got the same order through now and having the same problem, trying to find out the owner of the Bob on Discord.

**Pull request merged**
