### PR TITLE
Marketmaker v2

### PR DESCRIPTION
**Pull request by sindresorhus**
This a continuation of #563.

The intention of this PR is to get HyperDEX with mm2 in a workable state.

I'm currently testing against mm2 `d794c7b22`.

Current plan:

- [x] Use the new `rpc_password` field:
	- https://github.com/KomodoPlatform/developer-docs/blob/mm/docs/basic-docs/atomic-swap-dex/dex-walkthrough.md#initiate-marketmaker-20
	- https://github.com/artemii235/SuperNET/commit/39b25fbe2023d1d979515acc598f6de687a02acb
- [x] Successfully login to the portfolio.
- [ ] Update the currency info with data about `mm2` compatibility.
- [x] Create build script to fetch mm2 release from http://195.201.0.6/mm2/
	In HyperDEX, probably using a custom marketmakerVersion field in package.json, we would commit the version number or Git SHA of the Marketmaker version we use, so to have reproducible builds and ability to go back in history. We would also cache Marketmaker builds locally, so they're only downloaded once.
- [x] Successfully do a trade.

---

Found new docs: https://github.com/KomodoPlatform/developer-docs/tree/mm/docs/basic-docs/atomic-swap-dex

### CODE REVIEW

**Comment by sindresorhus** [comment]
@artemii235 Are the `getendpoint` and `portfolio` endpoints implemented in mm2?

This is what I'm getting:

```
Request: {method: "getendpoint", port: 65161}
Response: 500 {error: "Empty result from stats_JSON"}
```

```
Request: {method: "portfolio"}
Response: 500 {error: "Empty result from stats_JSON"}
```

**Comment by sindresorhus** [comment]
In the mm2 codebase, `getendpoint` is commented out, so I guess not.

```rust
/*
        else if ( strcmp(method,"getendpoint") == 0 )
        {
            int32_t err,mode; uint16_t wsport = 5555; char endpoint[64],bindpoint[64];
            if ( juint(argjson,"port") != 0 )
                wsport = juint(argjson,"port");
            retjson = cJSON_CreateObject();
            if ( IPC_ENDPOINT >= 0 )
            {
                jaddstr(retjson,"error","IPC endpoint already exists");
                jaddnum(retjson,"socket",IPC_ENDPOINT);
            }
            else
//...
*/
```

**Comment by lukechilds** [comment]
Also, we make heavy use of the WebSocket port in mmv1 to get updates on trade status and update the UI. I didn't see any mention of WebSocket usage in the updated docs.

**Comment by lukechilds** [comment]
And +1 on committing MM commit hash. We need reproducible builds otherwise we're going to have a nightmare tracking down bugs.

**Comment by artemii235** [comment]
Hi, `getendpoint` and `portfolio` calls are not working right now. API was changed significantly, the docs can be found here: https://github.com/artemii235/developer-docs/blob/mm/docs/basic-docs/atomic-swap-dex/dex-api.md. Please note that docs might miss some calls still, I will actualize it on this week.

**Comment by sindresorhus** [comment]
This is good enough to merge now. I'll continue to push improvements to master. (Want to merge so we can start having nightly builds from master).

**Pull request merged**
