### PR TITLE
Add donate button

### PR DESCRIPTION
**Pull request by sindresorhus**
It's WIP as I still need to get the KMD and BTC address from Pondsea.

screen shot 2018-08-14 at 00 33 00
screen shot 2018-08-14 at 00 32 56

### CODE REVIEW

**Comment by lukechilds** [comment]
Looks great.

Could maybe do with a little more text, I'm not sure exactly what to put there but maybe something like:

>HyperDEX is a free Open Source project. You can help support to support HyperDEX development by donating to the following addresses.

**Comment by lukechilds** [comment]
Maybe throw a ❤️ emoji in there somehwere?

**Comment by sindresorhus** [comment]
How about this?

screen shot 2018-08-15 at 00 39 58


Btw, open source should not be capitalized when used in a sentence: https://english.stackexchange.com/questions/157178/capitals-or-not-for-open-source

**Comment by lukechilds** [comment]
That looks great.

>Btw, open source should not be capitalized when used in a sentence

Cool, did not know that, always thought it was like a title of a type of software.

**Comment by lukechilds** [comment]
Maybe move the ❤️ to the beginning of the text to match the first start modal title:

>✨ Thanks for Helping Us Test HyperDEX!

**Comment by sindresorhus** [comment]
> ✨ Thanks for Helping Us Test HyperDEX!

How about we change this one instead to have the emoji at the end? It's more common for emojis to be after the text. They're not icons. And with the heart it looks unaligned when it's in front:

screen shot 2018-08-15 at 01 06 47

**Comment by lukechilds** [comment]
Sure, makes sense.

**Comment by sindresorhus** [comment]
@lukechilds Ok. I'll do that later after this PR. The emoji in the intro modal is in the localized text, so changing the position of it will invalidate all the localizations for the string... I will look for a workaround.

**Comment by sindresorhus** [comment]
Is this good to go now?

**Review by lukechilds — APPROVED** [review]

**Comment by lukechilds** [comment]
Beautiful

**Review by elevatedmindset209702 — COMMENTED** [review]
A lil shaky ground at first but it becomes a little more clearer as you trug along. Understand it's code but what about a glossary or index of some kind for references along the way. Would make some things just a lil 
more ez don't you think?

**Pull request merged**
