### PR TITLE
Fetch swap history in `Dashboard`

### PR DESCRIPTION
**Pull request by kevva**
When logging in and viewing the recent activity on the dashboard, it'll show no activity since the trades aren't loaded yet. You have to go to the exchange or trades view for them to show up.

Ideally we would run the following code as soon as we're logged in https://github.com/atomiclabs/hyperdex/blob/master/app/renderer/containers/Exchange.js#L33-L46.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I'm aware of the problem. I've been meaning to refactor the swap history to be in AppContainer instead, but wanted to wait for the refactoring work @lukechilds commented he was working on a while ago, so not to conflict.

**Comment by lukechilds** [comment]
Which work was that, the cmc/fiat thing or something else?

**Comment by sindresorhus** [comment]
Yes, the fiat thing.

**Comment by lukechilds** [comment]
Ah, sorry, that got `git stash`ed in the mad rush for beta. I didn't think it was important for beta and didn't want to make a load of code changes just before the release.

I didn't make much progress on it.

**Pull request merged**
