### PR TITLE
Add PGP badge to readme linking to Keybase proofs

### PR DESCRIPTION
**Pull request by lukechilds**
Thought this looked cool.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Good idea!

Why is this one much longer than the ones suggested in https://github.com/keybase/keybase-issues/issues/849#issuecomment-198513202 and https://github.com/badges/shields/issues/1299 ?

**Comment by sindresorhus** [comment]
And vote this up: https://github.com/amio/badgen-service/issues/140

**Comment by lukechilds** [comment]
>Why is this one much longer?

32-bit PGP fingerprints are [trivial to brute force](https://evil32.com/) so I used the 64-bit PGP fingerprint.

**Comment by lukechilds** [comment]
Note to self: Update to https://badgen.net, when this is merged: https://github.com/amio/badgen-service/pull/141

**Pull request merged**
